# Generated by Django 4.2.2 on 2023-07-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField()),
                ('start_date', models.DurationField()),
                ('end_date', models.DurationField()),
                ('company', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.DurationField(),
        ),
    ]
