# Generated by Django 4.2.2 on 2023-07-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_experience_alter_education_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.IntegerField(),
        ),
    ]
