# Generated by Django 4.2.2 on 2023-07-09 19:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_alter_education_end_date_alter_education_start_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=12)),
                ('surname', models.TextField(max_length=12)),
                ('address', models.TextField(max_length=30)),
                ('tel', models.CharField(max_length=12)),
                ('web', models.TextField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('birthday', models.DateField()),
                ('city', models.TextField(max_length=12)),
                ('title', models.TextField(max_length=20)),
                ('degree', models.TextField(max_length=10)),
                ('text1', models.TextField(max_length=100)),
                ('text2', models.TextField(max_length=100)),
                ('text3', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter', models.TextField(max_length=20)),
                ('linkdin', models.TextField(max_length=20)),
                ('skype', models.TextField(max_length=20)),
                ('facebook', models.TextField(max_length=20)),
                ('instagram', models.TextField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2023), django.core.validators.MinValueValidator(1900)]),
        ),
        migrations.AlterField(
            model_name='education',
            name='grade',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2023), django.core.validators.MinValueValidator(1900)]),
        ),
        migrations.AlterField(
            model_name='education',
            name='university_name',
            field=models.TextField(max_length=70),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.TextField(max_length=70),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2023), django.core.validators.MinValueValidator(1900)]),
        ),
        migrations.AlterField(
            model_name='experience',
            name='role',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2023), django.core.validators.MinValueValidator(1900)]),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='skill',
            name='value',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
