# Generated by Django 4.2.2 on 2023-07-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_testimonials_alter_social_facebook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(max_length=30)),
                ('position', models.TextField(max_length=70)),
                ('testimonial', models.TextField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Profile picture')),
            ],
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='image',
            field=models.FilePathField(path='C:\\Users\\user\\Desktop\\Courses\\WomenCourse\\NEW\\Ani_Avagyan\\portfolio\\resume\\static\\assets\\img\\testimonials'),
        ),
    ]
