# Generated by Django 4.2.2 on 2023-07-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_test_alter_testimonials_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='resume/static/images', verbose_name='Profile picture'),
        ),
    ]
