# Generated by Django 4.2.2 on 2023-07-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_alter_test_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Users\\user\\Desktop\\Courses\\WomenCourse\\NEW\\Ani_Avagyan\\portfolio\\resume/static\\images', verbose_name='Profile picture'),
        ),
    ]
