# Generated by Django 4.2.2 on 2023-07-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_delete_test_alter_testimonials_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='year',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
