# Generated by Django 4.2.2 on 2023-07-12 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_personal_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='year',
        ),
    ]
