# Generated by Django 4.2.3 on 2023-07-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0014_testimonials_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
