# Generated by Django 4.2.2 on 2023-07-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0021_portfolioproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioproject',
            name='category',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='client',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
