# Generated by Django 4.2.2 on 2023-08-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0023_experience_description1'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='description2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='description3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='description4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
