# Generated by Django 4.2.4 on 2023-10-31 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0024_experience_description2_experience_description3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='social',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='social',
            name='linkdin',
        ),
        migrations.RemoveField(
            model_name='social',
            name='skype',
        ),
        migrations.RemoveField(
            model_name='social',
            name='twitter',
        ),
        migrations.AddField(
            model_name='social',
            name='github',
            field=models.TextField(default='a', max_length=70),
        ),
        migrations.AddField(
            model_name='social',
            name='linkedin',
            field=models.TextField(default='a', max_length=70),
        ),
        migrations.AddField(
            model_name='social',
            name='telegram',
            field=models.TextField(default='a', max_length=70),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description1',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experience',
            name='description2',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experience',
            name='description3',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experience',
            name='description4',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='experience',
            name='role',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='link',
            field=models.URLField(),
        ),
    ]
