# Generated by Django 4.2.4 on 2023-11-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0025_remove_social_facebook_remove_social_instagram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='age',
        ),
        migrations.AlterField(
            model_name='personal',
            name='title',
            field=models.TextField(max_length=21),
        ),
    ]
